### ISSUE TITLE
Check with no checks returns False

### ISSUE THREAD

**Issue by zoidbergwill** [yola/healthcheck#10]
### "Faulty" code: 
```Python
    # If any of critical checks failed, or all checks failed, system state
    # is False (means "bad").
    if failed_critical_checks or len(failed_checks) == len(self._checks):
        return False
```

https://github.com/yola/healthcheck/blob/master/healthcheck/healthcheck.py#L176-L179

This means that when there are no checks(`len(self._checks) == len(failed_checks)`), the function returns False.

**Comment by zoidbergwill** [comment]
And then raises a `500`. Not that I consider using it to do no checks is a popular use case.

**Comment by ekoval** [comment]
Taking this ticket to merge changes made by @AceFire6
